export const PageConfig = {
  moduleTitle: "Master Data",
  pageTitle: "Users",
  baseEnpoint: "/base/users",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: false,
  enableFilterTools: true,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "id",
      label: "Id",
      sortable: true,
      width: 90,
      is_show: true,
    },
    {
      key: "created_at",
      label: "Created At",
      sortable: true,
      width: "auto",
      is_show: false,
    },
    {
      key: "updated_at",
      label: "Updated At",
      sortable: true,
      width: "auto",
      is_show: false,
    },
    {
      key: "name",
      label: "Name",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "email",
      label: "Email",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "username",
      label: "Username",
      sortable: true,
      width: "auto",
      is_show: true,
    },
  ],
  formFilterFields: [
    {
      key: "name",
      label: "Name",
      type: "text",
      rules: [],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: [],
    },
  ],
  formFields: [
    {
      key: "name",
      label: "Name",
      type: "text",
      rules: ["required"],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: ["required"],
    },
    {
      key: "username",
      label: "Username",
      type: "text",
      rules: ["required"],
    },
  ],
}
