export const PageConfig = {
  moduleTitle: "Approval",
  pageTitle: "Workflow",
  pageCreate: "/approval/workflow/create",
  pageEdit: "/approval/workflow/edit",
  baseEnpoint: "/core/workflow-approvals",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: false,
  enableFilterTools: false,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "id",
      label: "Id",
      sortable: true,
      width: 90,
      is_show: true,
    },
    {
      key: "created_at",
      label: "Created At",
      sortable: true,
      width: "auto",
      is_show: false,
    },
    {
      key: "modul",
      label: "Modul",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "type",
      label: "Type",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "nik",
      label: "NIK",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "position",
      label: "Position",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "value",
      label: "Value",
      sortable: true,
      width: "auto",
      is_show: true,
    },
  ],
  formFilterFields: [
    {
      key: "name",
      label: "Name",
      type: "text",
      rules: [],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: [],
    },
  ],
  formFields: [
    {
      key: "id",
      label: "ID",
      type: "text",
      rules: ["required"],
    },
    {
      key: "type",
      label: "Type",
      type: "text",
      rules: ["required"],
    },
    {
      key: "value",
      label: "Value",
      type: "text",
      rules: ["required"],
    },
    {
      key: "nik",
      label: "NIK",
      type: "text",
      rules: ["required"],
    },
    {
      key: "name",
      label: "Name",
      type: "text",
      rules: ["required"],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: ["required"],
    },
    {
      key: "position",
      label: "Position",
      type: "text",
      rules: ["required"],
    },
  ],
}
