export const PageConfig = {
  moduleTitle: "Master Data",
  pageTitle: "Employee",
  baseEnpoint: "/core/employees",
  primaryKey: "nik",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: false,
  enableFilterTools: true,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: false,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "nik",
      label: "NIK",
      sortable: true,
      width: 90,
      is_show: true,
    },
    {
      key: "created_at",
      label: "Created At",
      sortable: true,
      width: "auto",
      is_show: false,
    },
    {
      key: "updated_at",
      label: "Updated At",
      sortable: true,
      width: "auto",
      is_show: false,
    },
    {
      key: "name",
      label: "Name",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "email",
      label: "Email",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "position",
      label: "Position",
      sortable: true,
      width: "auto",
      is_show: true,
    },
  ],
  formFilterFields: [
    {
      key: "nik",
      label: "NIK",
      type: "text",
      rules: [],
    }
  ],
  formFields: [
    {
      key: "nik",
      label: "Name",
      type: "text",
      rules: ["required"],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: ["required"],
    },
    {
      key: "position",
      label: "Position",
      type: "text",
      rules: ["required"],
    },
    {
      key: "needApprovals",
      label: "Total Need Approval",
      type: "count_data",
      rules: ["required"],
    },
    
  ],
}
