export const PageConfig = {
  moduleTitle: "Approval",
  pageTitle: "Transaction",
  pageCreate: "/approval/transaction/create",
  pageEdit: "/approval/transaction/edit",
  baseEnpoint: "/core/transactions",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: false,
  enableFilterTools: false,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: true,
  enableDetails: true,
  enableEdit: true,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "id",
      label: "Id",
      sortable: true,
      width: 90,
      is_show: true,
    },
    {
      key: "workflowApproval.modul",
      label: "Modul",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "createdBy",
      label: "Created NIK",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "byCreated.name",
      label: "Created Name",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "amount",
      label: "Amount",
      sortable: true,
      width: "auto",
      is_show: true,
    },
  ],
  formFilterFields: [
    {
      key: "workflowApproval.modul",
      label: "Modul",
      type: "text",
      rules: [],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: [],
    },
  ],
  formFields: [
    {
      key: "id",
      label: "ID",
      type: "text",
      rules: ["required"],
    },
    {
      key: "amount",
      label: "Amount",
      type: "text",
      rules: ["required"],
    },
    {
      key: "createdBy",
      label: "Created NIK",
      type: "text",
      rules: ["required"],
    },
  ],
}
