export const PageConfig = {
  moduleTitle: "Approval",
  pageTitle: "Need Approval",
  baseEnpoint: "/core/need-approvals",
  primaryKey: "id",
  maxBottomIndexDropdown: 2,
  enableSearchTools: true,
  enableExportTools: false,
  enableFilterTools: true,
  enableColumnTools: false,
  enableActions: true,
  enableCreate: false,
  enableDetails: true,
  enableEdit: false,
  enableDelete: true,
  enableBulkDelete: true,
  enablePagination: true,
  enableLimitPerPage: true,
  enableRefreshTable: false,
  listFields: [
    {
      key: "id",
      label: "Id",
      sortable: true,
      width: 90,
      is_show: true,
    },
    {
      key: "workflowApproval.name",
      label: "Modul",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "transaction.amount",
      label: "Transaction Amount",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "nik",
      label: "NIK",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "name",
      label: "name",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "email",
      label: "email",
      sortable: true,
      width: "auto",
      is_show: true,
    },
    {
      key: "transaction.byCreated.name",
      label: "Created Name",
      sortable: false,
      width: "auto",
      is_show: true,
    },
    {
      key: "transaction.byCreated.nik",
      label: "Created NIK",
      sortable: false,
      width: "auto",
      is_show: true,
    },
  ],
  formFilterFields: [
    {
      key: "nik",
      label: "NIK",
      type: "text",
      rules: [],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: [],
    },
  ],
  formFields: [
    {
      key: "id",
      label: "ID",
      type: "text",
      rules: ["required"],
    },
    {
      key: "email",
      label: "Email",
      type: "text",
      rules: ["required"],
    },
    {
      key: "nik",
      label: "NIK",
      type: "text",
      rules: ["required"],
    },
    {
      key: "name",
      label: "Name",
      type: "text",
      rules: ["required"],
    },
    {
      key: "position",
      label: "Position",
      type: "text",
      rules: ["required"],
    },
  ],
}
