//import { HOST_URL } from "constants/app.constant";
import { HOST_URL } from "constants/app.constant";
import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from "constants/navigation.constant";
import { NAV_LIST } from "./nav";

const navigationConfig = [
  {
    key: "home",
    path: "/home",
    title: "Home",
    translateKey: "nav.home",
    icon: "home",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },

  {
    key: "nav.gen",
    path: "/base",
    title: "Master Data",
    icon: "",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "nav.gen.Base.Users",
        path: "/base/users",
        title: "Users",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "nav.gen.Base.employee",
        path: "/base/employee",
        title: "Employee",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "nav.approval",
    path: "/approval",
    title: "Approval",
    icon: "",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "nav.approval.transaction",
        path: "/approval/transaction",
        title: "Transaction",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "nav.approval.workflow",
        path: "/approval/workflow",
        title: "Workflow",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "nav.approval.need_approval",
        path: "/approval/need-approval",
        title: "Need Approval",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  // {
  //   key: "maintanceMenu",
  //   path: "",
  //   title: "Maintance",
  //   translateKey: "nav.maintanceMenu.groupMenu",

  //   type: NAV_ITEM_TYPE_TITLE,
  //   authority: [],
  //   icon: "apps",
  //   subMenu: [
  //     {
  //       key: "maintanceMenu.monitoring",
  //       path: "",
  //       title: "Group collapse menu",
  //       translateKey: "nav.maintanceMenu.monitoring",
  //       icon: "groupCollapseMenu",
  //       type: NAV_ITEM_TYPE_COLLAPSE,
  //       authority: [],
  //       subMenu: [
  //         {
  //           key: "maintanceMenu.apidoc",
  //           path: "/maintance/apidoc",
  //           externalPath: HOST_URL + "/api/documentation",
  //           title: "Api Swagger",
  //           translateKey: "nav.maintanceMenu.apidoc",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //         {
  //           key: "maintanceMenu.telescope",
  //           path: "/maintance/telescope",
  //           title: "Telescope",
  //           externalPath: HOST_URL + "/telescope",
  //           translateKey: "nav.maintanceMenu.telescope",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //         {
  //           key: "maintanceMenu.logviewer",
  //           path: "/maintance/logs",
  //           externalPath: HOST_URL + "/logs",
  //           title: "Log Viewer",
  //           translateKey: "nav.maintanceMenu.logviewer",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //         {
  //           key: "maintanceMenu.horizon",
  //           path: "/maintance/horizon",
  //           externalPath: HOST_URL + "/horizon",
  //           title: "Horizon",
  //           translateKey: "nav.maintanceMenu.horizon",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //         {
  //           key: "maintanceMenu.mailpit",
  //           path: "/maintance/mailpit",
  //           externalPath: "http://localhost:8025",
  //           title: "MailPit",
  //           translateKey: "nav.maintanceMenu.mailpit",
  //           icon: "",
  //           type: NAV_ITEM_TYPE_ITEM,
  //           authority: [],
  //           subMenu: [],
  //         },
  //       ],
  //     },
  //   ],
  // },
]

export default navigationConfig;
